name: Run CI tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt update
      - run: sudo apt install autoconf-archive lcov texlive
      - name: Cache GNU GMP builds
        id: cache-gmp
        uses: actions/cache@v4
        with:
          path: .local
          key: ${{ matrix.os }}-${{ hashFiles('scripts/*') }}
      - run: sh scripts/cibw_before_all.sh
        if: steps.cache-gmp.outputs.cache-hit != 'true'
      - run: autoreconf -if
      - run: ./configure -q --enable-gcov
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/.local/lib/pkgconfig
      - run: |
          make -s CFLAGS="-Wall -Wpedantic -Werror -std=c17 -Wconversion"
          make -s check CFLAGS="-Wall -Wpedantic -Werror -std=c17 -Wconversion"
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/.local/lib
      - run: lcov --capture --directory . --output-file coverage.info
      - run: genhtml coverage.info --output-directory coverage
      - run: make -s distcheck
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/.local/lib
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            coverage/
            coverage.info
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov_include: '*.c'
          gcov_args: --no-external
          fail_ci_if_error: true
