name: Run CI tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt update
      - run: sudo apt install autoconf-archive lcov texlive
      - name: Cache GNU GMP builds
        id: cache-gmp
        uses: actions/cache@v4
        with:
          path: .local
          key: ${{ matrix.os }}-${{ hashFiles('scripts/*') }}
      - run: sh scripts/cibw_before_all.sh
        if: steps.cache-gmp.outputs.cache-hit != 'true'
      - run: autoreconf -if
      - run: ./configure -q --enable-gcov
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/.local/lib/pkgconfig
      - run: |
          make -s CFLAGS="-Wall -Wpedantic -Werror -Wconversion"
          make -s check CFLAGS="-Wall -Wpedantic -Werror -Wconversion"
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/.local/lib
      - run: |
          lcov --capture --directory . \
               --output-file coverage-${{ matrix.os }}.info
      - uses: actions/upload-artifact@v6
        with:
          name: coverage-${{ matrix.os }}
          path: |
            coverage-${{ matrix.os }}.info
          retention-days: 1
      - run: make -s distcheck
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/.local/lib
  merge-coverage:
    runs-on: ubuntu-24.04
    needs:
      - tests
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: sudo apt update
      - run: sudo apt install lcov diff-cover
      - uses: actions/download-artifact@v7
        with:
          pattern: coverage-*
          merge-multiple: true
      - run: |
          genhtml coverage*.info --hierarchical \
            --output-directory coverage
      - run: |
          diff-cover coverage*.info --fail-under=100 \
            --compare-branch=origin/master
      - uses: actions/upload-artifact@v6
        with:
          name: coverage
          path: |
            coverage/
            coverage*.info
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          gcov_include: '*.c'
          gcov_args: --no-external
          fail_ci_if_error: true
